### ISSUE TITLE
Missing tags on github

### ISSUE THREAD

**Issue by stollr** [pnpm/symlink-dir#50]
I hope this is the right place to ask this question.

Today I got an error in a third party cli tool that uses symlink-dir per npx remotely (`npx symlink-dir ...`). But since version 6 requires node >= 18 the command suddenly failed. I came here to the Github repo and couldn't find the new release/tag for 6.0. But it is available at npmjs.com.

Now, my question is why there are different versions/tags on Github (https://github.com/pnpm/symlink-dir/tags) compared to npmjs (https://www.npmjs.com/package/symlink-dir?activeTab=versions)?

**Comment by zkochan** [comment]
As far as I know node.js 16 is already not supported by the node.js team since summer last year, so you should upgrade to node.js 18.

I have pushed the tag to github.

**Comment by stollr** [comment]
You are right about the support of node 16. but this wasn't my point 😉

It was just the missing tags. thanks for pushing them.
